version: '3'
services:
    db:
        image: "postgres:12.3"
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: senkapaj_root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: senkapaj_core
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:9080
